### ISSUE TITLE
Unable to reproduce reported UDA results on VisDA-C dataset.

### ISSUE THREAD

**Issue by Bostoncake** [tim-learn/SHOT-plus#3]
Would you please provide the commands used to reproduce the results on VisDA-C dataset? Your paper stated that the result for SHOT-IM++ and SHOT++ is 85.0 and 87.3 respectively, but I could only get 82.8~ by running `python image_source.py --output ckps/source/ --da uda --gpu_id 1 --dset VISDA-C --net resnet101 --lr 1e-3 --max_epoch 10 --s 0` and `python image_target.py --cls_par 0.3 --da uda --dset VISDA-C --gpu_id 0 --s 0 --output_src ckps/source/ --output ckps/target/ --net resnet101 --lr 1e-3` for training. Thanks.

**Comment by tim-learn** [comment]
> Would you please provide the commands used to reproduce the results on VisDA-C dataset? Your paper stated that the result for SHOT-IM++ and SHOT++ is 85.0 and 87.3 respectively, but I could only get 82.8~ by running `python image_source.py --output ckps/source/ --da uda --gpu_id 1 --dset VISDA-C --net resnet101 --lr 1e-3 --max_epoch 10 --s 0` and `python image_target.py --cls_par 0.3 --da uda --dset VISDA-C --gpu_id 0 --s 0 --output_src ckps/source/ --output ckps/target/ --net resnet101 --lr 1e-3` for training. Thanks.

Sorry for the late reply due to the CVPR ddl. Maybe you need to check about the python environment like versions provided in the SHOT https://github.com/tim-learn/SHOT. 

Best

**Comment by Leesoon1984** [comment]
> 



> Would you please provide the commands used to reproduce the results on VisDA-C dataset? Your paper stated that the result for SHOT-IM++ and SHOT++ is 85.0 and 87.3 respectively, but I could only get 82.8~ by running `python image_source.py --output ckps/source/ --da uda --gpu_id 1 --dset VISDA-C --net resnet101 --lr 1e-3 --max_epoch 10 --s 0` and `python image_target.py --cls_par 0.3 --da uda --dset VISDA-C --gpu_id 0 --s 0 --output_src ckps/source/ --output ckps/target/ --net resnet101 --lr 1e-3` for training. Thanks.



> 

Have you solved this issue? I have the same problem.

**Comment by tim-learn** [comment]
Hi, @Leesoon1984 @Bostoncake 

You can try the detailed command in the updated readme.md for reproducing results for VISDA-C.

Best

**Comment by chenxi52** [comment]
I have the same problem.
