### ISSUE TITLE
About performance of Source-only ++ 

### ISSUE THREAD

**Issue by tiangarin** [tim-learn/SHOT-plus#4]
First of all, thank you for your outstanding work.
I have a question about the performance of Source-only ++(SHOT++), which is superior than Souce-only (SHOT) with a large margin.
But I didn't see the difference with SHOT in the image_source script.
Is this performance evaluted after executing "python image_mixmatch.py --ps 0.0 --cls_par 0.0 --model source --gpu_id $1 --s $s --output_tar "ckps/s"$2 --output "ckps/mm"$2 --seed $2 --dset office --max_epoch 100"? Is this trained using target data?

**Comment by tim-learn** [comment]
> First of all, thank you for your outstanding work. I have a question about the performance of Source-only ++(SHOT++), which is superior than Souce-only (SHOT) with a large margin. But I didn't see the difference with SHOT in the image_source script. Is this performance evaluted after executing "python image_mixmatch.py --ps 0.0 --cls_par 0.0 --model source --gpu_id $1 --s $s --output_tar "ckps/s"$2 --output "ckps/mm"$2 --seed $2 --dset office --max_epoch 100"? Is this trained using target data?

Yes, you are right! Source-only++ utilized the target data via MixMatch, which could be also considered as a black-box UDA method.
